### ISSUE TITLE
Nao abre

### ISSUE THREAD

**Issue by delmarado** [henr1q/BomberBot#1]
Oi, Quando abro o executavel do bot abre uma janela de comandos mas fecha apos alguns segundos e nao faz nada, tem ideia do que possa ser? obrigado

**Comment by henr1q** [comment]
Tenta ver o erro que está dando antes de fechar. Você provavelmente não configurou o settings.ini, ou fez alguma coisa errada no arquivo. Entra no telegram que é a melhor forma de te ajudar.
